### ISSUE TITLE
Migration to noble-secp256k1

### ISSUE THREAD

**Issue by paulmillr** [cybercongress/cyb-snap#3]
Hey there. I've been digging through the network of users of noble-secp, and stumbled upon your package.

Seeing this:

```
  // TODO research why secp256k1 produce wrong sig
  // const sig = secp256k1.sign(hash, PRIV_KEY, {recovered: false, canonical: true})
  // const compPubKey = secp256k1.getPublicKey(PRIV_KEY, true)
  // const check = secp256k1.verify(sig, hash, compPubKey) // true!
```

I want to fix any issues in noble. What exactly is wrong in the snippet?

cc @litvintech

**Comment by cyborgshead** [comment]
Hello, @paulmillr 
I'm tried to use noble-secp256k1 against secp256k1-node because of it's zero-dependency nature 
But failed here cause noble-secp256k1  produce sig different from ecp256k1-node which I used starting this project.
And sig from ecp256k1-node successfully pass node verification but noble's not 
It will be awesome if you may help and support me with full migration to noble

**Comment by paulmillr** [comment]
could you give me an example of PRIV_KEY and hash where the signatures are different? Also, are you making sure both are using canonical form?

**Comment by paulmillr** [comment]
@litvintech Try 0.4.0, i've added deterministic signatures and 10,000+ test vectors.
